version: "3.8"

services:
  grpc-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-grpc-app:latest
    # Request all GPUs from the host
    gpus: all
    ports:
      - "50051:50051"
    environment:
      # Ensure the container sees all GPUs
      - NVIDIA_VISIBLE_DEVICES=all